### ISSUE TITLE
Text/Cursor desynchronized when typing at the same time.

### ISSUE THREAD

**Issue by rafeautie** [yjs/y-monaco#2]
**Describe the bug**
**Behavior 1:** When two users are typing at the same time. The cursor that is farthest down the page moves up with every key press.

**Behavior 2:** When two users are typing at the same time. The text gets out of sync. (i.e. one user has many lines of line breaks, the other does not)

**To Reproduce**
1. Go to 'https://rafe-dev-bp41knwx5.vercel.app/code'
2. Click on 'Connect'
3. Connect two users to the same room
4. Type at the same time

**Expected behavior**
Behavior 1 and 2 do not happen. I expect one person type to not affect another persons cursor

**Environment Information**
 - Chrome
 - yjs ^13.3.0
 - y-webrtc ^10.1.6
 - y-monaco ^0.0.1
 - react-monaco-editor ^0.39.1

**Additional context**
Im willing to assist in reproducing the issue. It might be difficult to do alone. Let me know so we can coordinate a time.

**Comment by akosyakov** [comment]
> Behavior 1: When two users are typing at the same time. The cursor that is farthest down the page moves up with every key press.

try to remove this code: https://github.com/yjs/y-monaco/blob/e17d9bc0a61a4c788efd2ae0ac8f441b53afa44c/src/y-monaco.js#L150-L156 Monaco can handle how cursor should be moved while editing. For me it gives better results.

> Behavior 2: When two users are typing at the same time. The text gets out of sync. (i.e. one user has many lines of line breaks, the other does not)

I've observed the same issue with yjs in another context. Not sure that it is related to Moanco integration.

**Comment by akosyakov** [comment]
I wonder about this line: https://github.com/yjs/y-monaco/blob/e17d9bc0a61a4c788efd2ae0ac8f441b53afa44c/src/y-monaco.js#L165 Monaco provides edits which should be applied to the previous version in the given order to get new results, changing order of edits can give different result.

@dmonad Could you clarify please why it is important to reorder them fro yjs? 🙏

**Comment by dmonad** [comment]
Hi @akosyakov 

Monaco used to have a very confusing representation of changes.

Starting with the doc `"ab"` and the changes object `[{ pos: 0, insert: '1' }, { pos: 1, insert: '2' }]`, the resulting document should be `"1a2b"`. You are expected to apply the changes as one atomic operation. I reorder the operations by decreasing positions to ensure that the operations can be applied on the Yjs model.

Nowadays, Monaco already sorts the operations and my sort implementation won't have any effect.

I might be wrong about this. But this is how I understood monaco changes.

I fixed the cursor issue. Thanks for notifying me. I only test that the documents synchronize. The most recent yjs release has a breaking change that breaks cursor synchronization in monaco and prosemirror.

But I can't reproduce any syncing issues. I opened your app and I also tried locally. Please open a separate ticket with a description on how to reproduce it. If you don't know how to exactly reproduce it, please try to make a recording of the issue. I already have several automatic tests for the monaco binding. There is probably an edge case (on the event object?) I'm not considering.

**Comment by dmonad** [comment]
I published the fix in y-monaco@0.1.0

**Comment by stefan-egorov** [comment]
There still seems to be issues, If both collaborators start with a blank state(not on different lines), editor selects whole blocks of text. Will try to make a test-case for it.

**Comment by akosyakov** [comment]
> Starting with the doc "ab" and the changes object [{ pos: 0, insert: '1' }, { pos: 1, insert: '2' }], the resulting document should be "1a2b". You are expected to apply the changes as one atomic operation. I reorder the operations by decreasing positions to ensure that the operations can be applied on the Yjs model.

@dmonad Monaco expects to apply a consequent change to a document resulted from an application of a previous change. Do I understand correctly that Yjs expects to apply all changes to the original content?

I'm not sure reordering monaco changes like that is safe. (Although it should be probably alright if all changes are happening from typing, not from programmatic edits) If one does not use transact then changes are applied in the same manner as by Monaco but each change result in an update event?

**Comment by dmonad** [comment]
Reordering is still necessary in Monaco pre version 17. I implemented multiple teats that confirm that Monaco also orders changes by position. So the current approach should still work.

I will stop reordering only if it causes bugs to keep supporting older versions.

Changes within a Yjs transaction only produce a single event. Otherwise there is no difference whether you use a transaction or several smaller updates.

**Comment by stefan-egorov** [comment]
> There still seems to be issues, If both collaborators start with a blank state(not on different lines), editor selects whole blocks of text. Will try to make a test-case for it.

Ignore this. I noticed `beforeAllTransactions` handler wasn't being invoked, apparently it was very recently introduced in `yjs` and I wasn't on the latest version. All good now, cheers!
